apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: oci
    chartRepository: oci://523883733847.dkr.ecr.eu-west-1.amazonaws.com
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: babadofar
    repository: jx3-k3s-vault-demo
  - key: staging
  ingress:
    domain: 192.168.64.2.nip.io
    ignoreLoadBalancer: true
    kind: ingress
    namespaceSubDomain: .jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: babadofar
  repository: bucketrepo
  secretStorage: vault
  vault: {}
  webhook: lighthouse
