filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: https://babadofar.github.io/jx3-k3s-vault-demo/
releases:
- chart: dev/spring-demo
  version: 0.0.10
  name: spring-demo
  values:
  - jx-values.yaml
- chart: dev/node-demo
  version: 0.0.2
  name: node-demo
  values:
  - jx-values.yaml
- chart: dev/grandma
  version: 0.0.2
  name: grandma
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
