# Source: grandma/charts/node-demo-gm/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grandma-node-demo-gm
  labels:
    draft: draft-app
    chart: "node-demo-gm-0.0.2"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'grandma'
    wave.pusher.com/update-on-config-change: 'true'
  namespace: jx-staging
spec:
  selector:
    matchLabels:
      app: grandma-node-demo-gm
  replicas: 1
  template:
    metadata:
      labels:
        draft: draft-app
        app: grandma-node-demo-gm
    spec:
      serviceAccountName: grandma-node-demo-gm
      volumes:
        - name: config-volume
          configMap:
            name: configjs
      containers:
        - name: node-demo-gm
          image: "ghcr.io/babadofar/node-demo:0.0.2"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config
          env:
            - name: VERSION
              value: 0.0.2
          envFrom: null
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1
              memory: 1524Mi
            requests:
              cpu: 0.1
              memory: 128Mi
      terminationGracePeriodSeconds:
      imagePullSecrets:
