# Source: grandma/charts/spring-demo-gm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-demo
  labels:
    chart: "spring-demo-gm-0.0.10"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'grandma'
  namespace: jx-staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: grandma-spring-demo-gm
